# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: My CI

on:
  push:
    branches: [ main ]

jobs:
  test_all_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9   
    - name: Test with unittests
      run: |
        python3 -m unittest tests/*.py -v
